### ISSUE TITLE
Improve the notification templates in order add the possibility to add a classification label

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1156]
It has been requested by Transparency-TI to improve the notification templates in order add the possibility to add a classification label.

The idea is that analyzing a tip the receiver(s) could assign a label to the tip in order to identify further submission in relation to an opened case.

**Comment by vecna** [comment]
assign a label from a defined group of possible labels, or assign an arbitrary string ? the second was requested also by @infosquatter

**Comment by fpietrosanti** [comment]
Their use-case is only to use a single label to receive the Subject line of notification to have the label they applied (if present) such as "ComuneRozzano" or "AppaltoXYZ":
Subject: [Notification: $progressive $label]

**Comment by vecna** [comment]
Ok, good, than is the same requested from @infosquatter (use cases: when you deal with a lots of tip, you don't recognize them. this mean that also the "preview field" is not the proper solution, and in the beginning has been planned for this reason)

**Comment by evilaliv3** [comment]
yep i confirm that the aim of this ticket is to simply assign a label to the tip chosen by receivers.
the tip will have one and one only label that all the receivers will have the possibility to configure(initially) and edit (after first assignment).

the label when assigned will need to availably as templateing variable in mail notifications (%TipLabel%) and shown on preview.

the concept is that this will be used of assig cases IDs in reference to others db used by organizations (legal cases, etc..) and its different from the concept you had in past @vecna in order to assign labels.

**Comment by vecna** [comment]
just to be clear: editing is in the tip status page, and the label is display after in the tip list ? is a PUT operation in receivertip that influence internaltip ? can we keep track of the chanes with a system comment ? duplicated label are acceptable (I suggest:yes)

**Comment by fpietrosanti** [comment]
Displaying a label on tip-list shall be another ticket

**Comment by evilaliv3** [comment]
The label should be configurable by receivers on the tip page and and show
on them too.

It showd be shown on the tip page, available on mail notifications and on
tip list. No need to spawn multiple tickets as this is really few changes
that relate to a sigle feature. I failed in opening the ticket due to
mobility but the feature needed to address it are the one I've described
till now.

I've already added a sigle variable to internaltip that I will push in next
db change. When we will switch to e2e encryption the variable will be put
in receivertip as probably fields like this will need to be always
encrypted for each receiver. I will open a ticket in order to analyze and
describe all the changes that will be needed for e2e encryption.

@vecna for what concern system comments the implementation we did was a
fast hack that for various reasons cant work now.  (E.g. When on tip page
we show only private messages we are currently not able to show comments
without additional logic. for this and other reasons i suggest to stop
using them and opening a ticket where to discuss about logs and logs
visibilities that are the generalization of this

**Comment by vecna** [comment]
@evilaliv3 verychiaro.it

**Comment by evilaliv3** [comment]
@vecna / @fpietrosanti : i want you to think to this doubts of mine:

1) do we dant this label to be unique per Tip or multiple for each receiver Tip? the first solution has drawbacks in multi stakeolder initiatives like Publeaks. the latter has drawback in single cohesive small groups like IRPI/TI

2) do we want this label to be internationalizable? i think not it would be realle difficult to be used by receivers. obviously not permitting this has a drawbacks but i would like to go for simplicity now.

**Comment by fpietrosanti** [comment]
1) I think that the request from TI of a label is "Per Receive on a single Tip" and it's something that the Receiver decide to type as a free-text when working on the Tip (e.g.:Giorgio decide that this tip is related to AppaltoXYZ and tag it as "AppaltoXYZ" or it's related to Comune di Rozzano, so he tag as "ComuneRozzano")

2) It's not internationalized because it's typed by the Receiver on the tip

**Comment by evilaliv3** [comment]
ok in case this is implemented per receiver i agree.

the issue is only if they want the label to be per Tip cause it will be a problem for multi stakeolder initiatives. for the moment so i modify the db so to accept a single per receiver and non internationalized "label".

**Comment by evilaliv3** [comment]
Db support for this ticket has been implemented adding an attribute 'label' to the receiverTip table so that now what is missing is basically the handler that would allow a user to apply a label to the tip.

**Comment by vecna** [comment]
clear, but I guess we want permit the editing from the single Tip and the display of the label in the tiplistpage ?

**Comment by evilaliv3** [comment]
Exactly, single tip, receiver specific (receiver tip) and so exported only
in the receiver tip).

For what relates the api I would if I would use the same we are using for
the postpone and delete that was thought by me on order to host other
operations like this (assign_label)

Sounds good?

We can work on iterating on it a bit so that one can perform with a single
request multiple operations in the following ux fashion:
.
- I click on an edit button or I perform a certain input in an area
- as I edit things the clients logs the actions I want to perform
- when I click an explicit save all my edits are applied performing a
request on this api with the ordered list of operations that I've executed

**Comment by vecna** [comment]
Yes, only "problem" I see, is in the notification side. We need to have a [%Label%] that sometime can be empty ? or better we can:

  * use the number randomly assigned as Label by default
  * when the Label is set, overwrite the number

And via graphical communication, we can make clear that the number can be changed (for example, is in grey, or stay inside a text area until changed)

**Comment by evilaliv3** [comment]
I think that keeping things separated would be best even for making people
understand the fearures

Let me align you on what discussed with naif:
- the random number is going to be removed
- the random will be replaced with the yearmonthday-sequencenumberinside
the day assigning so a protocol to the ticket not leaking the total number
but only eventually the daily number
- the label would be addressed by this ticket and yes it would be possible
for it to be empty

**Comment by vecna** [comment]
clear, I'm working on it.

**Comment by vecna** [comment]
I'm facing a very weird issue here with the validation, uploaded the code in the branch anti-dos-research at the moment.

**Comment by evilaliv3** [comment]
Nice @vecna but please make comments that add some value.

This comment addsu alarmism but does not tell anything at all

**Comment by vecna** [comment]
### Intro

i've changed the DELETE operation to assign an hardcoded Label, was intended to test the hanlder before implement the client side. This operation, is not working:

![image](https://cloud.githubusercontent.com/assets/89555/9654151/11b05cfc-5229-11e5-9361-ae8f4364bb8c.png)

The error is "InvalidInputFormat" (dict expected):

![image](https://cloud.githubusercontent.com/assets/89555/9654156/26bc0cae-5229-11e5-84f3-70d82095b3e1.png)

The content sent is:

      {"operation":"label","label":"ciaociaoXX"}

The validation **works**:

      2015-09-03 10:45:32+0200 [D] Authentication OK (receiver)
      2015-09-03 10:45:32+0200 [D] Updating ReceiverTip label from [] to ciaociaoXX
      2015-09-03 10:45:32+0200 [ ] 406 PUT /rtip/fda58a53-2aad-41ed-8fc4-bbe0f2efb4f5 (127.0.0.1): GLException
      2015-09-03 10:45:32+0200 [http] 406 PUT /rtip/fda58a53-2aad-41ed-8fc4-bbe0f2efb4f5 (127.0.0.1) 10.74ms

because the execution flow reach the transact:

        @transact
        def assign_rtip_label(store, user_id, tip_id, label_content):
            rtip = db_access_tip(store, user_id, tip_id)
            log.debug("Updating ReceiverTip label from [%s] to %s" % (rtip.label, label_content))
            rtip.label = unicode(label_content)

And the handler has this code:

         if request['operation'] == 'label':
             yield assign_rtip_label(self.current_user.user_id, tip_id, request['label']) 
         self.set_status(202)  # Updated
         self.finish()

so, I don't see much sense on what is happening, if some new kind of validation is in place, but the result is this:

      {"error_message": "Invalid Input Format [(label) dict expected]", "error_code": 10, "arguments": ["(label) dict expected"]}

**Comment by vecna** [comment]
Found, in the models you've declared the mock version of 'label' as Unicode(validator=shortlocal_v) but shortlocal is used only for localized JSON and don't apply to Unicode.

**Comment by vecna** [comment]
done, will be proposed PR along all the others improvement of anti-dos branch

**Comment by evilaliv3** [comment]
okay!

**Comment by evilaliv3** [comment]
@vecna unit test is missing here. can you implement it?

**Comment by vecna** [comment]
yes, today

**Comment by vecna** [comment]
done above

**Comment by evilaliv3** [comment]
well done @vecna 

from my point of view this time you were be able to still continue working on the same branch ADI+1156 intregrating the pull request but thanks for trying to split the branches;

**Comment by evilaliv3** [comment]
@fpietrosanti / @vecna: do you find ok that we show the label info also to the whistleblower?

i'm thinking that this may help in whistleblower/receiver communication wherever the whistleblower has done multiple submissions and they want refer them.

**Comment by evilaliv3** [comment]
ah no, this is not possible at all as the label is per-receiver so every receiver will label it for it's personal use.

for refering to a submission while discussing with the whistleblower/other receivers a receiver may simply use the tip sequence number that will act as a globaleaks protocol number shared among all users: https://github.com/globaleaks/GlobaLeaks/issues/1158

**Comment by evilaliv3** [comment]
Here we go!

![screenshot from 2015-09-07 11 32 58](https://cloud.githubusercontent.com/assets/217034/9714292/481de814-5557-11e5-81c8-71aa06ddfa68.png)
![screenshot from 2015-09-07 11 33 01](https://cloud.githubusercontent.com/assets/217034/9714297/4f0cfe58-5557-11e5-8e5b-11a504f8b9b3.png)
![screenshot from 2015-09-07 11 35 44](https://cloud.githubusercontent.com/assets/217034/9714302/55dd985a-5557-11e5-89e5-baedced9e449.png)
![screenshot from 2015-09-07 11 35 46](https://cloud.githubusercontent.com/assets/217034/9714304/58cbc078-5557-11e5-8172-6c6a3524158a.png)

@vecna look at the commit to learn how to do the things that you wanted to do.

**Comment by fpietrosanti** [comment]
Sent from mobile

> On 07/set/2015, at 10:53, Giovanni Pellerano <notifications@github.com> wrote:
>  Fra
> @fpietrosanti / @vecn: do you find ok that we show the label info also to the whistleblower?
> 
No, as we do not have a concept of multiple submissions from the same Whistleblower

**Comment by evilaliv3** [comment]
The label is now configurable; We simply miss to export it in mail templates.

When dealing with this ticket it would be easy to deal also with https://github.com/globaleaks/GlobaLeaks/issues/1158

**Comment by evilaliv3** [comment]
Feature implementation completed!

The traditional mail subject prefixed by [Tip NUM] is now replaced by [YYYYMMDD-SEQ] as done in ticket #1158 

When the receiver configure also a label (e.g. Pino Cammino) the subject will appear the following

"[20151105-1] [Pino Cammino] New submission"
"[20151105-1] [Pino Cammino] New comment"
"[20151105-1] [Pino Cammino] New file attachment"
