### ISSUE TITLE
Same table repeated twice when consulting a submission as a Whistleblower

### ISSUE THREAD

**Issue by PiemP** [globaleaks/GlobaLeaks#2167]
**Current behavior**
When you go to see your submission (acting as Whistleblower) with the key code or by push the button in the page of post submission I see the first table repeated.

Seems that in this page there is the table code and then there is a call to a template with angularjs that repeat this table twice.

Sorry for my written english. I hope is this understandable.

**Expected behavior**
see the first table only once

**Steps to reproduce the problem or feature illustration**
Check your submission with your key code or with the button on the page after sending the submission form

**GlobaLeaks version:**
2.72.31

**Browser:**
every browser

**Server Operating System and Version (if applicable):**
Debian 8.10 

**Client Operating System and Version (if applicable):**
Windows 10 Pro 64 1709

**Comment by evilaliv3** [comment]
Thank you @PiemP for reporting this.

Could you please verify if on the latest version (3.0.0) you are getting the same error?

**Comment by PiemP** [comment]
I receive this error when I run apt-get upgrade:

E: Failed to fetch http://deb.globaleaks.org/jessie/globaleaks_3.0.0_all.deb Size mismatch

**Comment by evilaliv3** [comment]
thanks for reporting this @PiemP;

it should be fixed now.

could you please try again?

**Comment by PiemP** [comment]
Ok, the size mismatch error is fixed but when I run apt-get update I receive this notification:

W: GPG error:  http://deb.globaleaks.org jessie/ Release: the following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key < ingo@globaleaks.org>

now I test the original issue

**Comment by evilaliv3** [comment]
Got it what happened that caused the whole failure in the release procedure

It is just a type mistake; We are now proceeding with a new release and i will be back in few minutes.

Thanks!

**Comment by evilaliv3** [comment]
It should be fine @PiemP, thank you for you patience.

**Comment by PiemP** [comment]
The issue is still here in 3.0.0 version

**Comment by evilaliv3** [comment]
i see.

could you please provide a screenshot or other useful information for reproducing the issue?

**Comment by PiemP** [comment]
![1](https://user-images.githubusercontent.com/2736009/36596143-0bb32cfe-18a5-11e8-8236-f905d6924da3.png)
![2](https://user-images.githubusercontent.com/2736009/36596145-0bd1a030-18a5-11e8-885b-fb8c9e379767.png)

**Comment by PiemP** [comment]
1- do a submission as Whistleblower
2- click on the button on the first screenshot (or use your submission code) to view the submission and you are redirected to the last screenshot with the first table repeated twice

**Comment by evilaliv3** [comment]
Bug confirmed, going to issue a patch that will be included in release 3.0.1

**Comment by evilaliv3** [comment]
Fixed!

**Comment by PiemP** [comment]
the problem is still here in 3.0.2 version

![sketch](https://user-images.githubusercontent.com/2736009/36676158-32bacfce-1b0b-11e8-948a-6f536d4c11e9.png)

**Comment by PiemP** [comment]
fixed in the 3.0.5 version 👍
