### ISSUE TITLE
Not being able to create a new user

### ISSUE THREAD

**Issue by Stephane-FILTRALA** [globaleaks/GlobaLeaks#2266]
**Current behavior**
Cannot create a new user. ERROR: Username already in use

**Expected behavior**
Being able to create a new user

**Steps to reproduce the problem or feature illustration**
![screenshot 2018-05-03 20 21 42](https://user-images.githubusercontent.com/37292195/39595700-c0ae08be-4eff-11e8-8743-ee6590d79831.jpg)

![screenshot 2018-05-03 20 21 49](https://user-images.githubusercontent.com/37292195/39595779-f3b61292-4eff-11e8-934d-615b6ce85b70.jpg)

**GlobaLeaks version:**
3.0.27

![screenshot 2018-05-03 20 21 57](https://user-images.githubusercontent.com/37292195/39595657-a8559b1a-4eff-11e8-99d6-638dfe58d877.jpg)

**Browser:**
﻿TorBrowser 7.5.3 (based on Mozilla Firefox 52.7.3) (64-bit) for OSX

**Server Operating System and Version (if applicable):**
¿?

**Comment by evilaliv3** [comment]
Thank you @Stephane-FILTRALA for reporting this.

The bug has been already identified and should be already fixed by https://github.com/globaleaks/GlobaLeaks/commit/33285a7b41049e935f3c6c0a27a8750935439297

This patch will be included in next release: 3.0.28

**Comment by Stephane-FILTRALA** [comment]
All right, @evilaliv3. Thnak you

**Comment by Stephane-FILTRALA** [comment]
We are now in in version 3.1.8 and still happens. Cannot create receivers.

**Comment by NCommander** [comment]
I took a look under the hood to see what triggers that error; it's pretty specific on what will cause that error:

```
    user = session.query(models.User).filter(models.User.tid == tid, models.User.username == text_type(request['username'])).one_or_none()
    if user is not None:
        raise errors.InputValidationError('Username already in use')
```

Reopening this ticket.

**Comment by evilaliv3** [comment]
Hello @Stephane-FILTRALA @infosquatter,

i rechecked the codebase and i confirm that the fix for this but was already applied but for some reasons your setup may need manual fix.

I'm producing a patch that would enable you to recheck on the issue and i will try to be back to you today with instructions.

**Comment by Stephane-FILTRALA** [comment]
Ok, @evilaliv3 Thank you!

**Comment by evilaliv3** [comment]
Update:

The current codebase is fine but your particular setup  may include a bug
triggered in the past.

By today we will release a fix that should help bypass the condition and
allow new users to be created.
This fix will make not necessary any of the following.

If you want you may anticipate the release removing lines 86, 87 and 88
from
https://github.com/globaleaks/GlobaLeaks/blob/master/backend/globaleaks/handlers/admin/user.py
and restarting globaleaks.

Cause of the bug is probably an existing user with an empty username.

To verify it properly you may perform the following:
- make a backup of the full /var/globaleaks directory
- open /var/globaleaks/globaleaks.db with sqlitebrowser
- check the user table and identify users with an empty username
- if confirmed to fix it completely you may set user.username equal as
user.id for the user with empty username.

**Comment by Stephane-FILTRALA** [comment]
Ok, @evilaliv3. I'll tell @infosquatter to have a look and we'll let you know if change the code or wait for the patch. Cheers!!

**Comment by evilaliv3** [comment]
Closing the ticket as probably outdated.

Feel free to re-open it if this is not the case.

**Comment by Stephane-FILTRALA** [comment]
Sorry but still doesn't work. We are not able to create a new user. 

![screenshot 2018-07-16 16 05 31](https://user-images.githubusercontent.com/37292195/42762992-1595d464-8912-11e8-95a9-d7b00ecf23a9.jpg)

![screenshot 2018-07-16 16 05 27](https://user-images.githubusercontent.com/37292195/42763003-199312d4-8912-11e8-8b56-912c663e92fe.jpg)

When we try to create an user we get this in the admin email: 

Platform: Buzón de filtraciones seguro y anónimo Fíltrala
Host: filtrala.awp.link (m56sg5xhl5wu52lk.onion)
Version: 3.1.9

sqlalchemy.exc.IntegrityError Wraps a DB-API IntegrityError.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 110, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/user.py", line 65, in create_receiver_user
    receiver, user = db_create_receiver_user(session, state, tid, request, language)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/user.py", line 54, in db_create_receiver_user
    user = db_create_user(session, state, tid, request, language)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/user.py", line 120, in db_create_user
    session.flush()

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2027, in flush
    self._flush(objects)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2145, in _flush
    transaction.rollback(_capture_exception=True)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2109, in _flush
    flush_context.execute()

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)

IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.tid, user.username [SQL: u'INSERT INTO user (id, tid, creation_date, username, password, salt, name, description, role, state, last_login, mail_address, language, password_change_needed, password_change_date, auth_token, enc_prv_key, enc_pub_key, can_edit_general_settings, change_email_address, change_email_token, change_email_date, reset_password_token, reset_password_date, pgp_key_fingerprint, pgp_key_public, pgp_key_expiration) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (u'b7fac8f0-1c97-45e3-baba-c535448f6fbb', 1, '2018-07-16 14:03:27.463263', u'', u'31680d502deccc82a328929e52f02de031744657c698b6a986b1eeff8fea04e55d8d9604ded6045b17e2ba8adf7bef2c8ecc0a10896499d0abc30b089e2cec2c', u'vJ4Bvb5NVq220bBlCcuREw==', u'test2001', u'{"es": ""}', u'receiver', u'enabled', '1970-01-01 00:00:00.000000', u'test2001@gmail.com', u'es', 1, '1970-01-01 00:00:00.000000', u'fedBmCbxhXFWYGxhe2Ouqom6qH6zZaXy', u'', u'', 0, u'', None, '3000-01-01 00:00:00.000000', None, datetime.datetime(3000, 1, 1, 0, 0), u'', u'', '1970-01-01 00:00:00.000000')]


Thanks!

**Comment by Stephane-FILTRALA** [comment]
I cannot reopen the issue. 
Thanks

**Comment by evilaliv3** [comment]
Thanks @Stephane-FILTRALA !

I've actually just managed to reproduce it!

The bug will be fixed in the upcoming relese (3.2.0); i will tell you as it will be out (in few hours max)

**Comment by evilaliv3** [comment]
@Stephane-FILTRALA, @infosquatter: i just issued a 3.2.0 that contains the proper fix for this issue.

Would you please try it?

**Comment by Stephane-FILTRALA** [comment]
Working correctly! 
Thank you!
