### ISSUE TITLE
Error when trying to import questionaire

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2421]
When trying to import a .json questionnaire (that I have previously exported) I get the following error message. Version 3.3.16. Browser Chrome.
I see the same behaviour on a try.globaleaks test implementation as well as on my own Ubuntu installation. Thanks

<img width="952" alt="2018-10-02" src="https://user-images.githubusercontent.com/23246886/46336515-b3faf400-c633-11e8-96cb-bfd8b28e5a2f.png">

**Comment by evilaliv3** [comment]
@elbill: by the chance do you have the globaleaks.log containing the related error?

The issue is that your exported questionnaire was taken by an old version of globaleaks and probably the internal data format is changed.
If you can report us the exact failure that was generated thius would be helpful for us to identify a solution!

thanks!

**Comment by elbill** [comment]
Cause l am out of office can you give me the exact path I can locate the
log file in the server? Or can I find it in the platform?

**Comment by elbill** [comment]
2018-10-16 14:17:36+0000 [-] [-] [1] 200 GET &#47;data&#47;field_attrs.json 1310B 1ms
2018-10-16 14:17:36+0000 [-] [-] [1] 200 GET &#47;admin&#47;node 3307B 0ms
2018-10-16 14:17:36+0000 [-] [-] [1] 200 GET &#47;admin&#47;questionnaires 3337B 115ms
2018-10-16 14:17:36+0000 [-] [-] [1] 200 GET &#47;admin&#47;fieldtemplates 4071B 185ms
2018-10-16 14:17:52+0000 [-] [E] Unhandled exception raised:
2018-10-16 14:17:52+0000 [-] [E] sqlalchemy.exc.IntegrityError Wraps a DB-API IntegrityError.&#92;n&#92;nTraceback (most recent call last):&#92;n&#92;n  Fil$
2018-10-16 14:17:52+0000 [-] [-] [1] 500 POST &#47;admin&#47;questionnaires?multilang=1 99B 13ms

**Comment by evilaliv3** [comment]
@elbill: Your issue should be probably fixed in current release 3.5.0.

Could you please recheck and let us know?

Thank you!

**Comment by elbill** [comment]
@evilaliv3 still the problem persists. I'm also attaching the questionnaire for you to confirm. It is a rather complex questionnaire
[Compliance.zip](https://github.com/globaleaks/GlobaLeaks/files/2678828/Compliance.zip)

.

**Comment by evilaliv3** [comment]
Thank you @elbill

Will check the questionnaire and evaluate which patch it is needed for
making it work and get sure the patch gets in the next release

**Comment by evilaliv3** [comment]
@elbill: i just rechecked your questionnaire.

It seems that it is using some question templates that you defined.

To fix your situation try first to reimport all your custom field templates and then reload this questionnaire.

Feel free to get back to us in case of any failure.

**Comment by evilaliv3** [comment]
Ah! Thank you @elbill with your feedback i just realized the issue.

I was considering implemented the feature for exporting/importing question templates but actually we miss this feature in the Question Templates section.

We will try to implement this in the short term and i estimate it could be included in the released package in 1 or 2 weeks.

I'm sorry for the temporary inconvenience.

**Comment by elbill** [comment]
Ok. I get it now. Just let me know when this will be ready.
Thanks!

**Comment by kituser** [comment]
Hi,

We are currently looking into adding a new context on our GlobaLeaks site, on a rather old version running 3.6.16. (I also get it on a 3.8 version) We have a test system and a production system on the same version with the exact same contexts. I am pretty sure this is not related to any specific version, since it shows up on both a 3.6 and a 3.8 version.

The system has been running for 1,5 year, and in daily use there are basically no issues.

When when trying to add a new context we get the 'Error! Internal Server Error! and in the globaleaks.log file the following shows up, explicitly on clicking create:

`2020-10-28 13:21:13+0100 [-] [E] Unhandled exception raised:

2020-10-28 13:21:13+0100 [-] [E] sqlalchemy.exc.IntegrityError Wraps a DB-API IntegrityError.\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 721, in _commit_impl\n    self.engine.dialect.do_commit(self.connection)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 443, in do_commit\n    dbapi_connection.commit()\n\nsqlite3.IntegrityError: FOREIGN KEY constraint failed\n\n\nThe above exception was the direct cause of the following exception:\n\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext\n    result = inContext.theWork()\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext\n    return func(*args,**kw)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 119, in _wrap\n    session.commit()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 906, in commit\n    self.transaction.commit()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 465, in commit\n    t[1].commit()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1632, in commit\n    self._do_commit()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1663, in _do_commit\n    self.connection._commit_impl()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 723, in _commit_impl\n    self._handle_dbapi_exception(e, None, None, None, None)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception\n    exc_info\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise\n    raise value.with_traceback(tb)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 721, in _commit_impl\n    self.engine.dialect.do_commit(self.connection)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 443, in do_commit\n    dbapi_connection.commit()\n\nsqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) FOREIGN KEY constraint failed\n`

I have no problems adding a new questionaire, so there is no issues writing to the Sqlite3 database file. I also tried to do a integrity check of the database, which didn't show any signs of any issues.

Are there any requirements in Python versions and the different versions of GlobaLeaks software?

**Comment by kituser** [comment]
I think I found my issue.


Under Advanced settings, there weren't set any Default Questionaire, as a new context propably couldn't be created, since it didn't have any default settings....
> Hi,
> 
> We are currently looking into adding a new context on our GlobaLeaks site, on a rather old version running 3.6.16. (I also get it on a 3.8 version) We have a test system and a production system on the same version with the exact same contexts. I am pretty sure this is not related to any specific version, since it shows up on both a 3.6 and a 3.8 version.
>
