### ISSUE TITLE
Whistleblower identity data blank

### ISSUE THREAD

**Issue by davelip** [globaleaks/GlobaLeaks#2612]
**Current behavior**
The whistleblower send a submission with his identity data:

![image](https://user-images.githubusercontent.com/946249/60608300-6d534980-9dbf-11e9-9be8-4eee1098380d.png)

The receiver ask the custodian:

![image](https://user-images.githubusercontent.com/946249/60608334-81974680-9dbf-11e9-9896-57c261d1dc14.png)

The custodian authorize the receiver to view the identity data.

The receiver view only the placeholder of identity data and not the value.

![image](https://user-images.githubusercontent.com/946249/60608427-bc997a00-9dbf-11e9-9ae3-85d51ec7019d.png)

**Expected behavior**
All the identity data are visibile to receiver.

**Steps to reproduce the problem or feature illustration**
See the current behavior.

**GlobaLeaks version:**
3.9.8

**Browser:**
Chrome 70
Firefox

**Server Operating System and Version (if applicable):**
Ubuntu 18.04

**Client Operating System and Version (if applicable):**
Ubuntu 19.04
Windows 10

**Comment by evilaliv3** [comment]
@davelip: this is a recent bug that i discovered and should be fixed in 3.9.9.

Would you please try it and and confirm this?

**Comment by davelip** [comment]
@evilaliv3 we have tried with an old and a new submission, but the bug is still present in 3.9.9

**Comment by evilaliv3** [comment]
thank you for the feedback, i will proceed rechecking it an let you know.

**Comment by evilaliv3** [comment]
Bug identified and solved, patch included in release 3.9.10

**Comment by evilaliv3** [comment]
Bug identified and solved, patch included in release 3.9.10

**Comment by evilaliv3** [comment]
A

**Comment by evilaliv3** [comment]
Actually a minor correction is still needed to handle an other situation of bug, will integrate it in a 3.9.11

**Comment by evilaliv3** [comment]
Closing as fixed.
