### ISSUE TITLE
Gray footer ribbon "powered by Globaleaks"  stays on, while scrolling on receiver interface.

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2728]
Software version: 3.11.39, ubuntu 18.04 on all browsers

Gray footer ribbon "powered by Globaleaks"  stays on, while scrolling on receiver interface.
![interface](https://user-images.githubusercontent.com/23246886/69172336-501cde80-0b06-11ea-86b8-09e482e9a090.png)

**Comment by evilaliv3** [comment]
Thank you @elbill for reporting this defect.

This regression may be related to the usage of bootstrap 4.

We are still trting to figure out what to use to have a sticky footer that works on every platform.

I think for the moment we will have just to remove the sticky footer and leave it floating till we figure it out.

do you have any suggestion?

**Comment by evilaliv3** [comment]
Fixed removing the sticky footer that will now remain floating. 

The patch will be released by today with release 3.11.40.

Thank you again for your feedback @elbill!

**Comment by elbill** [comment]
@evilaliv3  problem persists with 3.11.41 on chrome and edge browsers.
