### ISSUE TITLE
Onionsites Have Disconnected after upgrade

### ISSUE THREAD

**Issue by j3pc0m** [globaleaks/GlobaLeaks#3554]
### What version of GlobaLeaks are you using?

From 4.11.5 to 4.12.3

### What browser(s) are you seeing the problem on?

Tor Browser

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

After upgrade to 4.12.3 Tor said:

Onionsite Has Disconnected

The most likely cause is that the onionsite is offline. Contact the onionsite administrator.

Details: 0xF2 — Introduction failed, which means that the descriptor was found but the service is no longer connected to the introduction point. It is likely that the service has changed its descriptor or that it is not running.

But https sites are working.

I try upgrade and update and the result is the same.

**Comment by gabllux** [comment]
I get the same error, but from a clean install of 4.12.3 on Debian 11. I'm new in this project and still reading through the documentation, does TOR require to open other ports besides 80 and 443?

**Comment by evilaliv3** [comment]
Thank you for reporting this malfunction. We are investigating it.

**Comment by evilaliv3** [comment]
Fixed.

The patch is going to be released in 4.12.5

**Comment by evilaliv3** [comment]
@gabllux : is the problem fixed for you?

@j3pc0m seems to still be having some issue but i think it is probably elated to some other things now.

**Comment by gabllux** [comment]
Hello, I've tried this morning and the problem was still persisting.
Now I did a clean install on Debian 11 of an older Globaleaks version with the command `./install-globaleaks.sh -v 4.11.5` and with this environment onion is correctly working.
I did a new clean install on Debian 12 of the latest version (`./install-globaleaks.sh`) and onion is not working. So far I can exclude that the issue is related to the version of Debian. I'm using fresh AWS EC2 instances without any mofication.
