### ISSUE TITLE
File viewer not working

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3625]
### What version of GlobaLeaks are you using?

4.13.6 - fresh installation on debian 12

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows, Linux

### Describe the issue

When one or more files are uploaded, files are not viewable by the receiver. they can be just downloaded.
Tried with .txt, pdf, jpg, png extensions.

**Comment by evilaliv3** [comment]
Fixed.

The correction will be included in release 4.13.8

**Comment by larrykind** [comment]
Hi,
still encountering this issue on 4.13.22, image files are correctly viewable, pdf do not.

**Comment by larrykind** [comment]
Hi, 
issue is still on 5.0.88. images and text are visible, pdf are not. Could you please fix for next minor? 
Thanks
