### ISSUE TITLE
Deleting of a local admin fails

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#3740]
### What version of GlobaLeaks are you using?

4.13.15

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Hi! Trying to delete a local admin account - getting the error below (Globaleaks.log)

2023-11-02 13:53:20+0000 [-] [E] Unhandled exception raised:
2023-11-02 13:53:20+0000 [-] [E] AttributeError Attribute not found.\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext\n    result = inContext.theWork()\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext\n    return func(*args,**kw)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 185, in _wrap\n    result = function(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 216, in tw\n    return f(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/user.py", line 93, in db_delete_user\n    elif user_to_be_deleted.crypto_escrow_prv_key and not user_session.cryptow_escro_prv_key:\n\nAttributeError: 'Session' object has no attribute 'cryptow_escro_prv_key'\n

**Comment by evilaliv3** [comment]
Thank you @schris-dk; This should be fixed in 4.13.16.

Would you please verify?

**Comment by schris-dk** [comment]
Still not working. Extract from Globaleaks.log

2023-11-02 14:09:57+0000 [-] [E] Unhandled exception raised:
2023-11-02 14:09:57+0000 [-] [E] AttributeError Attribute not found.\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext\n    result = inContext.theWork()\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext\n    return func(*args,**kw)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 185, in _wrap\n    result = function(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 216, in tw\n    return f(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/user.py", line 93, in db_delete_user\n    elif user_to_be_deleted.crypto_escrow_prv_key and not user_session.cryptow_escro_prv_key:\n\nAttributeError: 'Session' object has no attribute 'cryptow_escro_prv_key'\n

**Comment by evilaliv3** [comment]
Ah you are right, let me fix this right away and issue a new release with few other bugfixes.

**Comment by evilaliv3** [comment]
Closing as the issue has been fixed since release 4.13.17
